# Generated by Django 5.2.3 on 2025-07-15 14:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('reading_time', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DR')),
                ('published', models.DateTimeField(default=datetime.datetime(2025, 7, 15, 14, 45, 29, 505607, tzinfo=datetime.timezone.utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
                'indexes': [models.Index(fields=['-published'], name='blog_post_publish_493ec4_idx')],
            },
        ),
    ]
